# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    args: ["--allow-multiple-documents"]
  - id: mixed-line-ending
  - id: sort-simple-yaml
  - id: file-contents-sorter
  - id: trailing-whitespace
    files: ^\.github/workflows/|.*\.py$

# Python formatting
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black

# Ruff linter, replacement for flake8, pydocstyle, isort
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.8.6'
  hooks:
    - id: ruff
      args: [--fix, --show-fixes]
      exclude: src/prince_cr/cross_sections/_phenom_relations.py

# # Enable the following later
# # Python docstring formatting
# - repo: https://github.com/pycqa/pydocstyle
#   rev: 6.1.1
#   hooks:
#   - id: pydocstyle
#     files: prince_cr/[^_].*\.py
